M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-11-22T16:00:08+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-22T16:00:08+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X155.18Y-96.87
X155.18Y-102.65
M30
